# Generated by Django 5.2 on 2025-04-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estilos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estilos.estilo')),
            ],
        ),
    ]
