# Generated by Django 5.2 on 2025-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=50)),
                ('tendencia', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
